swagger: '2.0'
info:
  title: 'Zeus API documentation'
  version: '1.0'
host: 'zeus-staging.arttrend.asia'
basePath: '/'
schemes:
  - 'https'
consumes:
  - 'application/json'
produces:
  - 'application/json'
securityDefinitions:
  AccessToken:
    type: 'apiKey'
    name: 'access_token'
    in: 'query'
tags:
  -
    name: 註冊
  -
    name: 忘記密碼
  -
    name: 登入
  -
    name: 付費
  -
    name: 藝術家
  -
    name: 拍賣
  -
    name: 其他

security:
  -
    AccessToken: []
paths:
  /registers:
    $ref: 'paths/registers/index.yml'
  /registers/{register_id}:
    $ref: 'paths/registers/show.yml'
  /users/validates_account:
    $ref: 'paths/users/validates_account.yml'
  /passwords:
    $ref: 'paths/passwords/index.yml'
  /session:
    $ref: 'paths/session/index.yml'
  /products:
    $ref: 'paths/products/index.yml'
  /orders:
    $ref: 'paths/orders/index.yml'
  /orders/renew:
    $ref: 'paths/orders/renew.yml'
  /artists:
    $ref: 'paths/artists/index.yml'
  /artists/{artist_id}:
    $ref: 'paths/artists/show.yml'
  /artists/{artist_id}/futured_auctions/artworks_count:
    $ref: 'paths/artists/futured_auctions/artworks_count.yml'
  /artists/{artist_id}/top_artworks:
    $ref: 'paths/artists/top_artworks.yml'
  /artists/{artist_id}/artworks_count:
    $ref: 'paths/artists/artworks_count.yml'
  /artists/{artist_id}/artworks_stats:
    $ref: 'paths/artists/artworks_stats.yml'
  /artists/{artist_id}/toggle_favorite:
    $ref: 'paths/artists/toggle_favorite.yml'
  /exchange:
    $ref: 'paths/exchange/index.yml'
  /auctions:
    $ref: 'paths/auctions/index.yml'
  /auctions/years:
    $ref: 'paths/auctions/years.yml'
  /companies:
    $ref: 'paths/companies/index.yml'
